# to learn more about workflows, visit the link below:
# https://docs.github.com/en/actions/about-github-actions/understanding-github-actions

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh

    - name: Install SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: /usr/bin/bash -e {0}
    
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: List loaded SSH keys  # For debugging
      run: ssh-add -l

    - name: Add known hosts (DigitalOcean Droplet)
      run: |
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Debug SSH connection  # Optional Debugging Step
      run: |
        ssh -v gabi@${{ secrets.DROPLET_IP }} echo "SSH connection successful"

    - name: Deploy application via SSH
      run: |
        ssh -v -o StrictHostKeyChecking=no gabi@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/gabi/inspek-reporting-app    # Directory on your server where your app is located
          git pull origin main                  # Pull the latest changes from GitHub
          npm install                           # Install any new dependencies
          pm2 restart inspek-reporting-app      # Restart the app using PM2
        EOF
