# to learn more about workflows, visit the link below:
# https://docs.github.com/en/actions/about-github-actions/understanding-github-actions

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install dependencies and build React app
      run: |
        npm install
        npm run build  # Build the React app

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh

    - name: Install SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: /usr/bin/bash -e {0}
    
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add known hosts (DigitalOcean Droplet)
      run: |
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Deploy application via SSH and sync build files
      run: |
        ssh -o StrictHostKeyChecking=no gabi@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/gabi/inspek-reporting-app        # Navigate to the app directory
          git pull origin main                      # Pull the latest code
          npm install                               # Install any new backend dependencies
          rm -rf inspek-frontend/build              # Remove old build folder if exists
          EOF
          

    - name: Deploy application via SSH
      run: |
        ssh -o StrictHostKeyChecking=no gabi@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/gabi/inspek-reporting-app    # Directory on server where the app is located
          git pull origin main                  # Pull latest changes from GitHub
          npm install                           # Install any new dependencies
          pm2 restart app.js                    # Restart the app using PM2
        EOF
