name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh

    - name: Install SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        eval $(ssh-agent -s)
        ssh-add private_key.pem
    
    - name: List loaded SSH keys  # For debugging
      run: ssh-add -l   

    - name: Add known hosts (DigitalOcean Droplet)
      run: |
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Debug SSH connection  # Optional Debugging Step
      run: |
        ssh -v gabi@${{ secrets.DROPLET_IP }} echo "SSH connection successful"

    - name: Deploy application via SSH
      run: |
        ssh -v -o StrictHostKeyChecking=no gabi@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/gabi/inspek-reporting-app    # Directory on your server where your app is located
          git pull origin main                  # Pull the latest changes from GitHub
          npm install                           # Install any new dependencies
          pm2 restart inspek-reporting-app      # Restart the app using PM2
        EOF
